### PR TITLE
Made some changes to the staff page of the cs88 website

### PR DESCRIPTION
**Pull request by johnteng9**
Changes:

- Corrected some of the bios (ie they had junior when they are actually a senior, since they just copy pasted their bios from the previous semester)
- Added Naveen to the list of TAs, just needs a picture to be uploaded to the 61a repo

### CODE REVIEW

**Comment by HuanzhiMao** [comment]
Do you want to update the source file in the 61a repo as well?
Otherwise, when we build the next time, those changes will be overwritten :(

**Comment by johnteng9** [comment]
> Do you want to update the source file in the 61a repo as well? Otherwise, when we build the next time, those changes will be overwritten :(

I would, but I am not added to the 61a repo.

**Comment by HuanzhiMao** [comment]
You have access I believe.
image
image

**Comment by johnteng9** [comment]
> You have access I believe. image

Oh, cool. What exactly needs to be changed in the 61a repo source file?

**Comment by HuanzhiMao** [comment]
https://github.com/Cal-CS-61A-Staff/berkeley-cs61a/blob/master/src/web/data/staff.py

https://github.com/Cal-CS-61A-Staff/staff-images/pull/9

**Comment by johnteng9** [comment]
> https://github.com/Cal-CS-61A-Staff/berkeley-cs61a/blob/master/src/web/data/staff.py
> 
> [Cal-CS-61A-Staff/staff-images#9](https://github.com/Cal-CS-61A-Staff/staff-images/pull/9)

Awesome, I will make those changes asap.

**Pull request closed without merging**
